name: Test Suite

on:
  pull_request:
  push:
    branches: [ 1.x ]
  schedule: [ { cron: '0 8 * * *' } ]

jobs:
  static-analyze:
    name: "Static Analyze"
    uses: flow-php/actions/.github/workflows/composer-script-static-analyze.yaml@main

  tests:
    name: "Tests"
    strategy:
      fail-fast: false
      matrix:
        dependencies: [ locked, lowest, highest ]
        php-version: [ 8.1 ]
        operating-system: [ ubuntu-latest ]

    runs-on: ${{ matrix.operating-system }}

    services:
      elasticsearch:
        image: elasticsearch:7.17.2
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          tools: composer:v2
          php-version: ${{ matrix.php-version }}
          ini-values: memory_limit=-1
        env:
          COMPOSER_TOKEN: ${{ secrets.PRIVATE_REPOSITORY_ACCESS }}

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Tests
        run: composer test